spring.application.name=sale-service

server.port=${SALE_SERVICE_PORT}
server.servlet.context-path=/api

spring.datasource.url=${SALE_SERVICE_DATASOURCE_URL}
spring.datasource.username=${SALE_SERVICE_DATASOURCE_USERNAME}
spring.datasource.password=${SALE_SERVICE_DATASOURCE_PASSWORD}

spring.rabbitmq.addresses=${RABBITMQ_URI}

spring.data.mongodb.uri=${MONGODB_URI}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100
spring.data.web.pageable.one-indexed-parameters=false

product.service.url=${PRODUCT_SERVICE_URL}
user.service.url=${USER_SERVICE_URL}
