spring.application.name=sale-service

server.port=${SALES_SERVER_PORT}
server.servlet.context-path=/api

spring.datasource.url=${SALES_SPRING_DATASOURCE_URL}
spring.datasource.username=${SALES_SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SALES_SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SALES_SPRING_DATASOURCE_DRIVER_CLASS_NAME}

spring.rabbitmq.addresses=${SALES_SPRING_RABBITMQ_ADDRESSES}

spring.data.mongodb.uri=${SALES_SPRING_DATA_MONGODB_URI}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100
spring.data.web.pageable.one-indexed-parameters=false

product.service.url=${PRODUCT_SERVICE_URL}
user.service.url=${USER_SERVICE_URL}
