services:
  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 15
  mongodb:
    image: mongo:8.0
    container_name: ${MONGODB_CONTAINER_NAME}
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 240s
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: ${RABBITMQ_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "${RABBITMQ_PORT}:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 240s
  user-service:
    build:
      context: ./apps/user-service
      dockerfile: Dockerfile
    container_name: ${USER_SERVICE_CONTAINER_NAME}
    ports:
      - "${USER_SERVICE_PORT}:8080"
    environment:
      USER_SERVICE_DATASOURCE_URL: ${USER_SERVICE_DATASOURCE_URL}
      USER_SERVICE_DATASOURCE_USERNAME: ${USER_SERVICE_DATASOURCE_USERNAME}
      USER_SERVICE_DATASOURCE_PASSWORD: ${USER_SERVICE_DATASOURCE_PASSWORD}
      USER_SERVICE_DATASOURCE_DRIVER: ${USER_SERVICE_DATASOURCE_DRIVER}
      RABBITMQ_URI: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  product-service:
    build:
      context: ./apps/product-service
      dockerfile: Dockerfile
    container_name: ${PRODUCT_SERVICE_CONTAINER_NAME}
    ports:
      - "${PRODUCT_SERVICE_PORT}:8081"
    environment:
      PRODUCT_SERVICE_PORT: ${PRODUCT_SERVICE_PORT}
      PRODUCT_SERVICE_DATASOURCE_URL: ${PRODUCT_SERVICE_DATASOURCE_URL}
      PRODUCT_SERVICE_DATASOURCE_USERNAME: ${PRODUCT_SERVICE_DATASOURCE_USERNAME}
      PRODUCT_SERVICE_DATASOURCE_PASSWORD: ${PRODUCT_SERVICE_DATASOURCE_PASSWORD}
      RABBITMQ_URI: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
      MONGODB_URI: ${MONGODB_URI}
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
  sale-service:
    build:
      context: ./apps/sale-service
      dockerfile: Dockerfile
    container_name: ${SALE_SERVICE_CONTAINER_NAME}
    ports:
      - "${SALE_SERVICE_PORT}:8082"
    environment:
      SALE_SERVICE_PORT: ${SALE_SERVICE_PORT}
      SALE_SERVICE_DATASOURCE_URL: ${SALE_SERVICE_DATASOURCE_URL}
      SALE_SERVICE_DATASOURCE_USERNAME: ${SALE_SERVICE_DATASOURCE_USERNAME}
      SALE_SERVICE_DATASOURCE_PASSWORD: ${SALE_SERVICE_DATASOURCE_PASSWORD}
      RABBITMQ_URI: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
      MONGODB_URI: ${MONGODB_URI}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      PRODUCT_SERVICE_URL: ${PRODUCT_SERVICE_URL}
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
volumes:
  mysql_data:
  mongodb_data:
  rabbitmq_data: