segundum.application.usecases.RegisterUserUseCase=segundum.application.interactors.RegisterUserInteractor
segundum.application.usecases.UpdateUserProfileUseCase=segundum.application.interactors.UpdateUserProfileInteractor
segundum.application.usecases.DeleteUserUseCase=segundum.application.interactors.DeleteUserInteractor
segundum.application.usecases.GetUserProfileUseCase=segundum.application.interactors.GetUserProfileInteractor