spring.application.name=product-service

server.port=${PRODUCTS_SERVER_PORT}
server.servlet.context-path=/api

spring.datasource.url=${PRODUCTS_SPRING_DATASOURCE_URL}
spring.datasource.username=${PRODUCTS_SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${PRODUCTS_SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${PRODUCTS_SPRING_DATASOURCE_DRIVER_CLASS_NAME}

spring.rabbitmq.addresses=${PRODUCTS_SPRING_RABBITMQ_ADDRESSES}

spring.data.mongodb.uri=${PRODUCTS_SPRING_DATA_MONGODB_URI}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100
spring.data.web.pageable.one-indexed-parameters=false
