server.port=${PRODUCTS_SERVER_PORT}

spring.datasource.url=${PRODUCTS_SPRING_DATASOURCE_URL}

spring.jpa.hibernate.ddl-auto=none
spring.datasource.username=${PRODUCTS_SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${PRODUCTS_SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${PRODUCTS_SPRING_DATASOURCE_DRIVER_CLASS_NAME}

spring.rabbitmq.addresses=${PRODUCTS_SPRING_RABBITMQ_ADDRESSES}

spring.data.mongodb.uri=${PRODUCTS_SPRING_DATA_MONGODB_URI}