server.port=${PRODUCTS_SERVER_PORT:8081}

spring.datasource.url=${PRODUCTS_SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/products?serverTimezone=CET&createDatabaseIfNotExist=true}
spring.datasource.username=${PRODUCTS_SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${PRODUCTS_SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=${PRODUCTS_SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}

spring.rabbitmq.addresses=${PRODUCTS_SPRING_RABBITMQ_ADDRESSES:localhost:5672}

spring.data.mongodb.uri=${PRODUCTS_SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/segundum_read}