spring.application.name=product-service

server.port=${PRODUCT_SERVICE_PORT}
server.servlet.context-path=/api

spring.datasource.url=${PRODUCT_SERVICE_DATASOURCE_URL}
spring.datasource.username=${PRODUCT_SERVICE_DATASOURCE_USERNAME}
spring.datasource.password=${PRODUCT_SERVICE_DATASOURCE_PASSWORD}

spring.rabbitmq.addresses=${RABBITMQ_URI}

spring.data.mongodb.uri=${MONGODB_URI}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100
spring.data.web.pageable.one-indexed-parameters=false
