CREATE DATABASE IF NOT EXISTS sales;
USE sales;

CREATE TABLE IF NOT EXISTS event_store (
	id VARCHAR(255) PRIMARY KEY,
	aggregate_id VARCHAR(255) NOT NULL,
	type VARCHAR(255) NOT NULL,
	payload LONGTEXT NOT NULL,
	timestamp TIMESTAMP(6) NOT NULL
)